### ISSUE TITLE
desole windows path

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [JulienPalard/pospell#1]
Traceback (most recent call last):
  File "C:\Python34\Scripts\pospell-script.py", line 11, in <module>
    load_entry_point('pospell==0.0.3', 'console_scripts', 'pospell')
  File "C:\Python34\lib\site-packages\pospell.py", line 41, in main
    (tmpdir / po_file.name).write_text(po_to_text(str(po_file)))
AttributeError: 'WindowsPath' object has no attribute 'write_text'

idee?

**Comment by Abdur-rahmaanJ** [comment]
for me np, is >=3.5 popular enough. ok will use 3.5 with it ^^_
